### PR TITLE
Large player

### PR DESCRIPTION
**Pull request by P-man2976**
Added large player screen for large screen.

### CODE REVIEW

**Comment by P-man2976** [comment]
(Still WIP)

**Comment by uetchy** [comment]
Screen Shot 2022-04-05 at 22 13 41
Tip: You could convert the PR into a draft and put it back when it is ready for review.

**Comment by P-man2976** [comment]
Oh, thanks! I’ll convert this PR to draft.

**Comment by P-man2976** [comment]
I’m ready for merge!

**Review by sphinxrave — APPROVED** [review]

**Comment by sphinxrave** [comment]
LGTM, great work on the full screen display! Let's check it out in dev and see if there are any polish we want to add to it <3

**Pull request merged**
